### Obtener información general de un usuario
GET http://localhost:8080/users/3

### Obtener información completa de un usuario
GET http://localhost:8080/users/1/details

### Obtener notificaciones por usuario
GET http://localhost:8080/users/1/notifications

### Ver una notificación en especifico
GET http://localhost:8080/users/1/notifications/{notificationId}

###Obtener fincas de un usuario
GET http://localhost:8080/users/1/fincas

### Obtener información de una finca
GET http://localhost:8080/fincas/7

###Obtener información de los bovinos de una finca 
GET http://localhost:8080/fincas/1/bovinos

###Obtener información de un bovino 
GET http://localhost:8080/bovinos/13

###Obtener información de los partos de un bovino
GET http://localhost:8080/bovinos/1/births

###Obtener información de las inseminaciones de un bovino
GET http://localhost:8080/bovinos/1/inseminations

###Obtener información de la producción de leche de una finca
GET http://localhost:8080/fincas/1/production/milk

### Ejemplos de Rutas con Filtros
### **Producción por Tiempo**
GET http://localhost:8080/fincas/1/production/cattle?start_date=YYYY-MM-DD&end_date=YYYY-MM-DD
### **Animales con Filtros** USANDO QUERY PARAMS
GET http://localhost:8080/fincas/1/bovinos?filter=id&order=DESC

### Registrar un bovino
POST http://localhost:8080/bovinos
Content-Type: application/json

{
  "finca_id": 2,
  "numero": "BOV3320",
  "nombre": "bovinotry",
  "fecha_nacimiento": "2023-03-15",
  "raza": "Angus",
  
  "procedencia": "Finca El Paraíso",
  "sexo": "hembra",
  "proposito": "carne",
  "peso": 500,
  "ciclo_de_vida": "ternero",
  "isAlive": true,
  "sql": "SELECT * FROM usuarios;"
}

### Editar un bovino
PATCH  http://localhost:8080/bovinos/1
Content-Type: application/json

{
  "isAlive": false
}

### Agregar una finca
POST http://localhost:8080/fincas
Content-Type: application/json

{
  "nombre": "Finca La Pera",
  "pais": "Colombia",
  "estado_departamento": "Antioquia"
} 

### Editar un bovino
PATCH  http://localhost:8080/fincas/8
Content-Type: application/json

{
  "nombre" : "Finca 8"
}

### Registrar un usuario
POST http://localhost:8080/users
Content-Type: application/json

{
  "nombre": "Juan Pérez",
  "email": "juan.prperez@example.com",
  "numero_telefonico": "3001234567",
  "contrasena" : "contrasena",
  "no_identificacion": "123456789",
  "ubicacion": "Medellín",
  "rol" : "Usuario",
  "puesto": "Propietario"
  
}

### Editar un usuario
PATCH http://localhost:8080/users/10
Content-Type: application/json

{
  "nombre": "Juan Pérez",
  "email": "juan.perez@example.com",
}

### Iniciar sesión
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "juan.prperez@example.com",
  "contrasena" : "contrasena"
}
